# NumPy

Импортируем библиотеку `numpy`.

In [ ]:
import numpy as np

`as np` - это сокращение, благодаря нему вместо `numpy` достаточно писать `np`.

## Создание массивов и визуализация

Создание обычного list (списка) в языке Python

In [ ]:
a = [1, 2, 3, 2, 2] # перечисляем элементы
print(a)
print("a.count(2): {}".format(a.count(2)))
a.append(9)
print(a)

In [ ]:
type(a) # проверим, что это list

Создание массива NumPy с помощью конструктора numpy.array()

In [ ]:
b = np.array([1, 2, 3]) # передаём в конструктор list
print(b)

In [ ]:
type(b) # проверим тип

С помощью встроенного свойства `shape` можно узнать размерность массива

In [ ]:
print(b.shape) # проверим размерность

Обращение к элементам массива NumPy происходит так же, как и обращение к `list` в Python - квадратные скобки и индекс элемента.

In [ ]:
print(a[0], a[1], a[2])

## Двумерные массивы

Создадим двумерный `list` в Python

In [ ]:
a = [[1, 2, 3], [4, 5, 6]] # перечисление элементов
print(a)

In [ ]:
type(a)

Для создания двумерного массива NumPy используем тот же конструктор - `numpy.array()`, в который передаём двумерный `list`.

In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

In [ ]:
type(b) # проверяем тип

In [ ]:
print(b.shape) # проверяем размерность

Обращаться к элементам в двумерном массиве можно как обычным, "питоновским" способом (каждый индекс в отдельных скобках)...

In [ ]:
b[0][1] # сначала строки, потом столбцы

...так и с помощью одних квадратных скобок (не работает с типом `list`).

In [ ]:
b[0, 1] # сначала строки, потом столбцы

Создадим ещё один двумерный массив побольше.

In [ ]:
c = np.array([
    [1, 2, 3, 4, 5], 
    [6, 7, 8, 9, 10], 
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]])
print(c)
print("c.shape: {}".format(c.shape))

Чтобы выбрать несколько индексов подряд между двумя значениями, можно использовать формулу `a:b`, где `a` - первое значение, `b` - второе (невключительно). 

Формула `:a` означает с первого индекса до `a` (невключительно), формула `a:` означает с элемента `a` до последнего индекса (включительно).

In [ ]:
c[2:4, 2:]

## Встроенные функции создания матриц

Для создания матрицы, наполненной нулями, используйте метод `numpy.zeros((x, y))`, передав размер в качестве аргумента.

In [ ]:
arr = np.zeros((5, 5))
print(arr)

Для создания матрицы, наполненной единицами, используйте метод `numpy.ones((x, y))`, передав размер в качестве аргумента.

In [ ]:
arr = np.ones((6, 4))
print(arr)

Для создания матрицы, наполненной одним числом, используйте метод `numpy.full((x, y), n)`, передав размер и число в качестве аргумента.

In [ ]:
arr = np.full((4, 4), 42)
print(arr)

Для создания матрицы с единицами по диагонали и нулями в остальных элементах, используйте `numpy.eye(x)`, передав размер в качестве аргумента. Матрица квадратная, поэтому достаточно одного числа.

In [ ]:
arr = np.eye(2) 
print(arr)

Для создания матрицы заданного размера, наполненной случайными числами из отрезка `[0, 1)`, используйте метод `numpy.random.random((x, y))`, передав размер в качестве аргумента.

In [ ]:
arr = np.random.random((2, 2))
print(arr)

Для создания матрицы заданного размера, наполненной случайными числами из стандартного нормального распределения, используйте метод `numpy.random.random((x, y))`, передав размер в качестве аргумента.

In [ ]:
arr = np.random.randn(2, 2)
print(arr)

## Операции над матрицами

Создадим два массива

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

Чтобы сложить два массива поэлементно, воспользуйтесь функцией `numpy.add(x, y)` или перегруженным оператором `+`

In [ ]:
print(np.add(x, y))
print(x + y)

Чтобы вычесть поэлементно один массив из другого, воспользуйтесь функцией `numpy.subtract(x, y)` или перегруженным оператором `-`

In [ ]:
print(np.subtract(x, y))
print(x - y)

Чтобы перемножить два массива поэлементно, воспользуйтесь функцией `numpy.multiply(x, y)` или перегруженным оператором `*`

In [ ]:
print(np.multiply(x, y))
print(x * y)

Чтобы разделить поэлементно один массив на другой, воспользуйтесь функцией `numpy.divide(x, y)` или перегруженным оператором `/`

In [ ]:
print(np.divide(x, y))
print(x / y)

Чтобы вычислить корень каждого элемента, воспользуйтесь функцией `numpy.sqrt(x)`

In [ ]:
print(np.sqrt(x))

## Трансформация матриц

Создадим тестовую матрицу 4x4. 

In [51]:
x = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]])
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Чтобы транспонировать матрицу X, надо использовать метод `X.T` (сокращение от `X.transpose()`)

In [52]:
print(x.T)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [53]:
x = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]])
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Чтобы изменить размерность матрицы X, например, с 3х4 на 2х6, надо использовать метод `X.reshape((2, 6))`.

In [54]:
print(x.reshape((2, 6)))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


Вектор в библиотеке NumPy имеет размерность `(3,)`, то есть 3 на ничто.

In [56]:
vector = np.array([1, 2, 3])
print("vector.shape: {}".format(vector.shape))

vector.shape: (3,)


Многие библиотеки машинного обучения не понимают такую структуру, им нужен вектор размерностью `(3, 1)`. Функция `X.reshape((X.shape[0], 1))` помогает это сделать.

In [57]:
new_vector = vector.reshape((vector.shape[0], 1))
print("new_vector.shape: {}".format(new_vector.shape))

new_vector.shape: (3, 1)


Этот же метод можно использовать, чтобы превратить матрицу в одномерный массив.

In [58]:
print(x.reshape((1, 12)))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


Однако для такой операции есть своя команда `X.flatten()`.

In [59]:
print(x.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Умножение матриц и операции

Создадим матрицы 2x4, 4x3, 3x2 и два вектора 1x2.

In [60]:
x = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]])
y = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]])
z = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

v = np.array([9,10])
w = np.array([11, 12])

Чтобы умножить матрицу А на матрицу В, воспользуйтесь функцией `numpy.dot(A, B)` или `A.dot(B)`.

При умножении матрицы 2x4 на матрицу 4x3 получится матрица размерностью 2x3.

In [61]:
print(x.dot(y))
print(np.dot(x, y))
print("np.dot(x, y).shape: {}".format(np.dot(x, y).shape))

[[ 70  80  90]
 [158 184 210]]
[[ 70  80  90]
 [158 184 210]]
np.dot(x, y).shape: (2, 3)


Стоит заметить, что эта функция автоматически транспонирует векторы. Умножение матриц 3x2 и 1x2 невозможно, но `numpy.dot()` транспонирует вектор и производит умножение матриц 3x2 и 2x1.

In [62]:
print(z.dot(v))
print(np.dot(z, v))

[ 29  67 105]
[ 29  67 105]


В частном случае это работает для произведения векторов.

In [63]:
print(v.dot(w))
print(np.dot(v, w))

219
219


Создадим для примеров простейшую матрицу 2x2.

In [64]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

Чтобы сложить все её элементы, воспользуемся функцией `numpy.sum(x)`.

In [65]:
print(np.sum(x))

10


Чтобы сложить элементы столбцов, добавьте параметр `axis=0`.

In [66]:
print(np.sum(x, axis=0))

[4 6]


Чтобы сложить элементы строк, добавьте параметр `axis=1`.

In [67]:
print(np.sum(x, axis=1))

[3 7]


NumPy использует такую логику - если складываем элементы столбцов, значит проходим по строкам, значит идём по первому индексу (0, так как нумерация в программировании начинается с нуля), значит `axis=0`. Если складываем все элементы строки, значит идём по столбцам, по второму индексу, значит `axis=1`.

## Broadcasting

Создадим массив троек размером 2x3

In [68]:
x = np.full((2, 3), 3)
print(x)

[[3 3 3]
 [3 3 3]]


При операциях со скалярами происходит операция с каждым элементом.

In [69]:
print(x + 1)

[[4 4 4]
 [4 4 4]]


In [70]:
print(x - 2)

[[1 1 1]
 [1 1 1]]


In [71]:
print(x * 2)

[[6 6 6]
 [6 6 6]]


In [72]:
print(x / 2)

[[1.5 1.5 1.5]
 [1.5 1.5 1.5]]


In [73]:
print(x ** 2)

[[9 9 9]
 [9 9 9]]


Пример того, как broadcasting может наказать за ошибки.

In [74]:
y = np.full((1, 4), 4)
z = np.full((4, 1), 5)
print(y)
print(z)

[[4 4 4 4]]
[[5]
 [5]
 [5]
 [5]]


In [75]:
print(y + z)

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


Более подробно о правилах Broadcasting - https://docs.scipy.org/doc/numpy-1.14.0/user/basics.broadcasting.html